@apiKey = dev-token
@host = localhost:3000

# Global ping
GET http://{{host}}/api/ping
X-Api-Key: {{apiKey}}

###

# Introspect
GET http://{{host}}/api/introspect
X-Api-Key: {{apiKey}}

###

# DGFIP v1
GET http://{{host}}/api/impots/svair
    ?numeroFiscal={{$dotenv TEST_TAX_NUMBER}}
    &referenceAvis={{$dotenv TEST_TAX_NOTICE_NUMBER}}
X-Api-Key: {{apiKey}}

###

# DGFIP v2
GET http://{{host}}/api/v2/avis-imposition
    ?numeroFiscal={{$dotenv TEST_TAX_NUMBER}}
    &referenceAvis={{$dotenv TEST_TAX_NOTICE_NUMBER}}
X-Api-Key: {{apiKey}}

###

# CNAF v1
GET http://{{host}}/api/caf/famille
    ?numeroAllocataire={{$dotenv TEST_NUMERO_ALLOCATAIRE}}
    &codePostal={{$dotenv TEST_CODE_POSTAL}}
X-Api-Key: {{apiKey}}

###

# CNAF v2
GET http://{{host}}/api/v2/composition-familiale
    ?numeroAllocataire={{$dotenv TEST_NUMERO_ALLOCATAIRE}}
    &codePostal={{$dotenv TEST_CODE_POSTAL}}
X-Api-Key: {{apiKey}}

###

# Pôle Emploi v2
GET http://{{host}}/api/v2/situations-pole-emploi
    ?identifiant={{$dotenv TEST_POLE_EMPLOI_ID}}
X-Api-Key: {{apiKey}}

###

# MESRI v2 par INE
GET http://{{host}}/api/v2/etudiants
    ?ine={{$dotenv TEST_MESRI_INE}}
X-Api-Key: {{apiKey}}

###

# MESRI v2 par état civil
GET http://{{host}}/api/v2/etudiants
    ?nom={{$dotenv TEST_MESRI_NOM}}
    &prenom={{$dotenv TEST_MESRI_PRENOM}}
    &dateDeNaissance={{$dotenv TEST_MESRI_DATE_NAISSANCE}}
    &lieuDeNaissance={{$dotenv TEST_MESRI_LIEU_NAISSANCE}}
    &sexe={{$dotenv TEST_MESRI_SEXE}}
X-Api-Key: {{apiKey}}
