// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Pgmigrations = sequelize.define(
    'pgmigrations',
    {
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      runOn: {
        type: DataTypes.DATE,
        allowNull: false,
      },
    },
    {
      tableName: 'pgmigrations',
      underscored: true,
      timestamps: false,
      schema: process.env.DATABASE_SCHEMA,
    }
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Pgmigrations.associate = () => {};

  return Pgmigrations;
};
