version: '3.9'

services:
  postgres:
    image: timescale/timescaledb:latest-pg13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    network_mode: host
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://redis/
      NODE_ENV: development
      LOG_LEVEL: '1'
      ENV: local
      SANDBOXED: 'true'
      SENTRY_ENABLED: 'false'
    network_mode: service:db
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
