version: '3.9'

services:
  db:
    image: timescale/timescaledb:latest-pg13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5444:5432
  test-db:
    image: timescale/timescaledb:latest-pg13
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  cache:
    image: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      TEST_DATABASE_URL: postgres://postgres:postgres@test-db:5432/postgres
      REDIS_URL: redis://cache/
      NODE_ENV: development
      LOG_LEVEL: '1'
      ENV: local
      SANDBOXED: 'true'
      SENTRY_ENABLED: 'false'
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - db
      - cache

volumes:
  postgres-data:
